/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import DataBase.ConnectionTimeOutException;
import DataBase.DBOperations;
import Domain.Equipment;
import Domain.Sport;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Irfad Hussain
 */
public class AddEquipmentFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddEquipmentFrame
     */
    
    private AdminFrame parent;
    private DBOperations dbHandler;
    private ArrayList<Sport> sports;
    
    public AddEquipmentFrame(AdminFrame parent) {
        initComponents();
        this.parent = parent;
        this.dbHandler = DBOperations.getInstace();
        setLocationRelativeTo(parent);
        try {
            sports = dbHandler.loadSports();
            for(Sport sport:sports)
                cmbxSport.addItem(sport.getSportName());
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ConnectionTimeOutException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        cmbxAvailability = new javax.swing.JComboBox();
        txtPrice = new javax.swing.JTextField();
        cmbxCondition = new javax.swing.JComboBox();
        cmbxSport = new javax.swing.JComboBox();
        btnAddEquipment = new javax.swing.JButton();
        txtItemNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Equipment");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Type :");
        getContentPane().add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Purchase Date :");
        getContentPane().add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Availability :");
        getContentPane().add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Purchase Price :");
        getContentPane().add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Condition :");
        getContentPane().add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Sport :");
        getContentPane().add(jLabel6);
        getContentPane().add(txtType);

        cmbxAvailability.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Avilable", "Not Available" }));
        getContentPane().add(cmbxAvailability);
        getContentPane().add(txtPrice);

        cmbxCondition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Good", "Needs to be repaired", "Discarded" }));
        getContentPane().add(cmbxCondition);

        getContentPane().add(cmbxSport);

        btnAddEquipment.setText("Add Equipment");
        btnAddEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEquipmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddEquipment);
        getContentPane().add(txtItemNo);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Item No :");
        getContentPane().add(jLabel7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnAddEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEquipmentActionPerformed
        Equipment equipment = new Equipment();
        equipment.setItemNo((String)txtItemNo.getText());
        equipment.setType(txtType.getText());
        equipment.setPurchaseDate(new java.sql.Date(txtdate.getDate().getTime()));
        equipment.setPurchasePrice(Float.valueOf(txtPrice.getText()));
        equipment.setAvailability(cmbxAvailability.getSelectedIndex()==0);
        equipment.setCondition((String) cmbxCondition.getSelectedItem());
        equipment.setSportName((String) cmbxSport.getSelectedItem());
        try {
            dbHandler.addEquipment(equipment);
            JOptionPane.showMessageDialog(this, "Equipment Added Successfully.", "Operation Success", JOptionPane.INFORMATION_MESSAGE);
            parent.setEnabled(true);
            this.dispose();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error! Cannot add equipment. "+ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ConnectionTimeOutException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error! Cannot connect to database. "+ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddEquipmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEquipment;
    private javax.swing.JComboBox cmbxAvailability;
    private javax.swing.JComboBox cmbxCondition;
    private javax.swing.JComboBox cmbxSport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtItemNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
